
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[window]
padding = { x = 10, y = 10}
dynamic_padding = true
opacity = 0.9
decorations = "None"
blur = true

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
